/* Iron Week: local-first, versioned sessions. No remote dependencies. */
const KEY='ironweek_v2', $=id=>document.getElementById(id), uid=()=>crypto.randomUUID(), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=d=>{d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function weekKey(d){d=new Date(d);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return dateKey(d)}
function defaults(){return {schemaVersion:2,lifetimeXP:0,rewardPoints:0,sessions:[],active:null,rewards:[],redemptions:[],weeklyBonuses:[],preferences:{},notes:{},loads:{},settings:{weeklyGoal:3,setRest:75,compoundRest:120,exerciseRest:90,handleWeight:null,barWeight:null,plates:[4,4,4],workDays:[0,1,2,3,4],shiftStart:'22:00',shiftEnd:'07:00',sleep:'',wake:'',readiness:true},migration:{done:true}}}
function readData(){let raw=localStorage.getItem(KEY);if(raw){try{return validate(JSON.parse(raw))}catch(e){throw new Error('Saved data could not be read. It has been preserved. Export the raw data before restoring a backup.')}}let d=defaults();let xp=Number(localStorage.getItem('ironweek_xp'));d.lifetimeXP=Number.isFinite(xp)?Math.max(0,xp):0;let dates=[];try{dates=JSON.parse(localStorage.getItem('ironweek_completedDates')||'[]')}catch(e){}if(Array.isArray(dates))for(const day of [...new Set(dates)])if(/^\d{4}-\d{2}-\d{2}$/.test(day)&&dateKey(day+'T12:00:00')===day){let dow=new Date(day+'T12:00:00').getDay();d.sessions.push({id:'legacy-'+day,type:({2:'Push',3:'Pull',4:'Legs',5:'Push',6:'Pull',0:'Legs'})[dow]||'Rest',status:dow===1?'rest':'completed',legacy:true,date:day,startedAt:null,finishedAt:null,duration:0,exercises:[],xpEarned:0,rewardPointsEarned:0,rewarded:true})}d.migration={done:true,legacyXP:d.lifetimeXP,importedDates:d.sessions.length};localStorage.setItem(KEY,JSON.stringify(d));return d}
function validate(d){if(!d||d.schemaVersion!==2||!Array.isArray(d.sessions)||!Array.isArray(d.rewards)||!Array.isArray(d.redemptions)||!Number.isFinite(d.lifetimeXP)||d.lifetimeXP<0||!Number.isFinite(d.rewardPoints)||d.rewardPoints<0)throw Error('Invalid backup');let ids=new Set();for(let s of d.sessions){if(!s.id||ids.has(s.id)||!['completed','partial','rest'].includes(s.status)||!['Push','Pull','Legs','Rest'].includes(s.type)||!Array.isArray(s.exercises)||!Number.isFinite(s.duration)||s.duration<0)throw Error('Invalid session');ids.add(s.id);if(!s.legacy&&(!Number.isFinite(Date.parse(s.startedAt))||!Number.isFinite(Date.parse(s.finishedAt))))throw Error('Invalid timestamp');for(let e of s.exercises)if(!EXERCISES[e.exerciseId]||!Array.isArray(e.sets)||e.sets.some(x=>!Number.isFinite(x.reps)||x.reps<0||!Number.isFinite(x.duration)||x.duration<0||!Number.isFinite(x.weight)||x.weight<0))throw Error('Invalid sets')}for(let r of d.rewards)if(!r.id||typeof r.name!=='string'||!Number.isFinite(r.cost)||r.cost<=0)throw Error('Invalid reward');if(d.active&&(!['Push','Pull','Legs'].includes(d.active.type)||!Array.isArray(d.active.exercises)||!Number.isFinite(Date.parse(d.active.startedAt))))throw Error('Invalid active session');return {...defaults(),...d,settings:{...defaults().settings,...d.settings},preferences:d.preferences||{},notes:d.notes||{},loads:d.loads||{},weeklyBonuses:d.weeklyBonuses||[]}}
let db;try{db=readData()}catch(e){$('app').innerHTML=`<h1>Data preserved</h1><p>${esc(e.message)}</p><button onclick="download(localStorage.getItem(KEY),'ironweek-recovery.json')">Export saved data</button>`;throw e}let page='Dashboard',chosen=null,minimum=false,completion=null,selectedDate=dateKey(new Date()),historyMonth=new Date();
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));return true}catch(e){alert('Storage is full or unavailable. Your latest changes are still in this open app. Export a backup now.');return false}}
function toast(t){$('toast').textContent=t;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2600)}
const completed=()=>db.sessions.filter(s=>s.status==='completed'), sessionDate=s=>s.date||dateKey(s.startedAt), orderSessions=()=>[...db.sessions].sort((a,b)=>(b.startedAt||b.date).localeCompare(a.startedAt||a.date));
function nextType(){let s=orderSessions().find(s=>s.status==='completed'&&PROGRAMS[s.type]);return s?['Push','Pull','Legs'][(['Push','Pull','Legs'].indexOf(s.type)+1)%3]:'Push'}
function weeklyCount(key=weekKey(new Date())){return completed().filter(s=>weekKey((s.startedAt||s.date+'T12:00:00'))===key).length}
function streak(){let d=new Date();let n=0;if(weeklyCount()>=db.settings.weeklyGoal)n++;d.setDate(d.getDate()-7);for(let i=0;i<520;i++){if(weeklyCount(weekKey(d))<db.settings.weeklyGoal)break;n++;d.setDate(d.getDate()-7)}return n}
function statusDay(day){let ss=db.sessions.filter(s=>sessionDate(s)===day);return ss.some(s=>s.status==='completed')?'completed':ss.some(s=>s.status==='partial')?'partial':ss.length?'rest':''}
function fmtTime(s){return s.legacy?'Time not recorded':new Date(s.startedAt).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}
function elapsed(a){return Math.max(0,Math.floor(((a.pausedAt||Date.now())-Date.parse(a.startedAt)-(a.pausedMs||0))/1000))}
const mins=s=>Math.round(s/60), name=e=>e.variation||EXERCISES[e.exerciseId].name;
function navigate(p){page=p;render()}
function render(){if(db.active)hydrateWorkout();document.body.classList.toggle('working',!!db.active&&page==='Workout');$('nav').innerHTML=['Dashboard','Workout','History','More'].map(p=>`<button class="${page===p?'active':''}" onclick="navigate('${p}')">${p}</button>`).join('');$('headerHint').textContent=db.active?'SESSION IN PROGRESS':'YOUR OWN PACE';$('app').innerHTML=page==='Dashboard'?dashboard():page==='Workout'?workout():page==='History'?history():more()}
function calendar(days){return `<div class="calendar">${days.map(day=>`<button aria-label="${day}, ${statusDay(day)||'no workout'}" class="day ${statusDay(day)} ${day===dateKey(new Date())?'today':''}" onclick="openDay('${day}')">${Number(day.slice(-2))}</button>`).join('')}</div>`}
function dashboard(){let type=chosen||nextType(),last=orderSessions().find(s=>s.status==='completed'),count=weeklyCount(),level=Math.floor(db.lifetimeXP/300)+1,days=[];for(let i=29;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);days.push(dateKey(d))}let reward=db.rewards.find(r=>r.goal)||db.rewards[0],weekSessions=db.sessions.filter(s=>weekKey(s.startedAt||s.date+'T12:00:00')===weekKey(new Date()));let away=last?(Date.now()-new Date(last.startedAt||last.date+'T12:00:00'))/86400000:0;return `<div class="hero"><div class="row"><span class="eyebrow">${away>=14?'Welcome back':'Today'}</span><button class="text" onclick="choose()">Change</button></div><h1>${type}</h1><p class="muted">${chosen?'Your choice':'Recommended next'}</p><p class="muted">~${minimum?'15–20':'35–45'} min · ${minimum?3:5} exercises</p>${away>=14?'<small>+50 comeback XP available</small>':''}<button class="primary" onclick="${db.active?"resume()":"startCheck()"}">${db.active?'Resume Workout':'Start Workout'}</button></div><div class="stats"><div><strong>${streak()}</strong><small>week streak</small></div><div><strong>LVL ${level}</strong><small>${db.lifetimeXP.toLocaleString()} XP</small></div><div><strong>${completed().length}</strong><small>workouts</small></div></div><section class="section"><div class="row"><small>Last 30 days</small><small>${db.settings.weeklyGoal} / week goal</small></div>${calendar(days)}<small>Light: complete · muted: partial · dashed: recovery</small></section><section class="section"><small>Last Workout</small>${last?`<h2>${last.type}${last.minimum?' · Minimum':''}</h2><p class="muted">${fmtTime(last)}</p><small>${last.legacy?'Legacy entry · duration unknown':`${mins(last.duration)} min · ${last.exercises.filter(e=>e.sets.length).length} exercises`}</small>`:'<p>Your first session starts here.</p>'}<p class="muted">Next: ${nextType()}</p></section><section class="quiet"><div class="row"><span>This week</span><span>${count} / ${db.settings.weeklyGoal}</span></div><p class="muted">${mins(weekSessions.reduce((n,s)=>n+s.duration,0))} min trained · ${count>=db.settings.weeklyGoal?'goal reached':streak()?'streak intact · keep going':'building consistency'}</p></section>${reward?`<section class="quiet"><small>Saving for</small><p>${esc(reward.name)}</p><div class="progress"><i style="width:${Math.min(100,db.rewardPoints/reward.cost*100)}%"></i></div><small>${db.rewardPoints} / ${reward.cost} points</small></section>`:''}`}
function sheet(html){$('sheet').innerHTML=`<div class="row"><span></span><button class="text" onclick="closeSheet()" aria-label="Close details">Close</button></div>${html}`;$('sheet').showModal()}
function closeSheet(){$('sheet').close()}
function choose(){sheet(`<h2>Choose your session</h2>${['Push','Pull','Legs','Minimum Workout','Rest'].map(t=>`<div class="listrow"><button onclick="selectType('${t}')">${t}</button></div>`).join('')}`)}
function selectType(t){closeSheet();if(t==='Rest'){sheet('<h2>Recovery day</h2><p class="muted">Rest is part of the routine. Your rotation stays the same.</p><button class="primary" onclick="logRest()">Log Recovery</button>');return}minimum=t==='Minimum Workout';chosen=minimum?nextType():t;render()}
function logRest(){let day=dateKey(new Date());if(!db.sessions.some(s=>s.status==='rest'&&sessionDate(s)===day)){let now=new Date().toISOString();db.sessions.push({id:uid(),type:'Rest',status:'rest',startedAt:now,finishedAt:now,duration:0,exercises:[],xpEarned:0,rewardPointsEarned:0,rewarded:true});save()}closeSheet();render()}
function startCheck(){if(db.active){resume();return}if(!db.settings.readiness){startSession();return}sheet(`<h2>How are you feeling?</h2><p class="muted">Choose the session that fits today.</p><div class="chips">${['Low','Okay','Good'].map(r=>`<button onclick="ready('${r}')">${r}</button>`).join('')}</div>`)}
function ready(r){if(r==='Low'){sheet(`<h2>A little work counts.</h2><button class="primary" onclick="minimum=true;startSession()">Start Minimum Workout</button><button class="text" onclick="minimum=false;startSession()">Use full workout</button>`)}else startSession()}
function startSession(){if(db.active){resume();return}closeSheet();let type=chosen||nextType();let ids=(minimum?MINIMUM:PROGRAMS)[type];db.active={id:uid(),type,minimum,startedAt:new Date().toISOString(),pausedMs:0,pausedAt:null,index:0,side:0,stage:'warmup',warmIndex:0,flowVersion:1,exercises:ids.map(id=>({exerciseId:id,variation:db.preferences[id]||EXERCISES[id].variants[0],targetSets:minimum?2:EXERCISES[id].sets,sets:[],weight:db.loads[id]??EXERCISES[id].weight,difficultyFeedback:null,notes:db.notes[id]||''})),rest:null};save();page='Workout';completion=null;render()}
function resume(){page='Workout';render()}
function previous(e){return orderSessions().filter(s=>!s.legacy).flatMap(s=>s.exercises).find(x=>x.exerciseId===e.exerciseId&&x.variation===e.variation&&x.sets.length)}
function suggestion(e){let recent=orderSessions().filter(s=>s.status==='completed').flatMap(s=>s.exercises.filter(x=>x.exerciseId===e.exerciseId&&x.variation===e.variation&&x.sets.length)).slice(0,2);if(recent.some(x=>x.difficultyFeedback==='Uncomfortable'))return 'Try a comfortable substitute next time. Do not push through pain.';if(recent.some(x=>x.difficultyFeedback==='Very Hard'))return 'Keep the difficulty steady. Use a lighter load or easier variation if needed.';let def=EXERCISES[e.exerciseId];if(recent.length===2&&recent.every(x=>x.difficultyFeedback==='Easy'||x.sets.every(s=>(def.timed?s.duration:s.reps)>=def.range[1])))return 'Ready to progress · '+(def.next||'Consider a small load increase or slower, controlled reps.');return 'Try to beat one set while keeping clean, comfortable form.'}
function feedback(r){let a=db.active;a.exercises[a.index].difficultyFeedback=r;advance()}
function exerciseNav(){let a=db.active;sheet(`<h2>This session</h2>${a.exercises.map((e,i)=>`<div class="listrow"><button onclick="jumpExercise(${i})">${i+1}. ${esc(name(e))}<small> · ${e.sets.length} sets</small></button></div>`).join('')}<button class="text" onclick="closeSheet();reviewSession()">Review & finish</button>`)}
function exitSheet(){sheet(`<h2>Keep your progress</h2><p class="muted">Resume later or save what you have done as a partial session.</p><button class="primary" onclick="pauseExit()">Pause & resume later</button><button class="text" onclick="finishSession('partial')">Save partial workout</button>`)}
function reviewSession(){let a=db.active,done=a.exercises.every(e=>e.sets.length>=e.targetSets*(EXERCISES[e.exerciseId].sides?2:1));sheet(`<h2>${done?'Session ready':'Work saved so far'}</h2><p>${a.exercises.reduce((n,e)=>n+e.sets.length,0)} sets · ${mins(elapsed(a))} min</p><button class="primary" onclick="finishSession('${done?'completed':'partial'}')">${done?'Complete workout':'Save partial workout'}</button>${done?'':'<p class="muted">Complete all planned sets to log a full session. Minimum sessions count equally toward your weekly goal.</p>'}`)}
function prFor(a){let prs=[];for(let e of a.exercises){if(!e.sets.length||e.sets.some(s=>s.loadUnknown))continue;let def=EXERCISES[e.exerciseId],old=db.sessions.filter(s=>!s.legacy).flatMap(s=>s.exercises).filter(x=>x.exerciseId===e.exerciseId&&x.variation===e.variation).flatMap(x=>x.sets);for(let s of e.sets){let compatible=old.filter(x=>def.timed||x.weight===s.weight);let best=Math.max(0,...compatible.map(x=>def.timed?x.duration:x.reps)),v=def.timed?s.duration:s.reps;if(best>0&&v>best&&!prs.some(p=>p.exerciseId===e.exerciseId))prs.push({exerciseId:e.exerciseId,name:name(e),value:v,previous:best,weight:s.weight,timed:!!def.timed})}}return prs}
function finishSession(status){let a=db.active;if(!a||db.sessions.some(s=>s.id===a.id))return;let before=weeklyCount(),prs=prFor(a),doneExercises=a.exercises.filter(e=>e.sets.length>=e.targetSets*(EXERCISES[e.exerciseId].sides?2:1)).length;let xp=doneExercises*10+(status==='completed'?(a.minimum?80:120):0)+prs.length*25;let last=orderSessions().find(s=>s.status==='completed');if(status==='completed'&&last&&(Date.now()-new Date(last.startedAt||last.date+'T12:00:00'))/86400000>=14)xp+=50;let record={...a,status,finishedAt:new Date().toISOString(),duration:elapsed(a),prs,rewarded:true,xpEarned:xp,rewardPointsEarned:xp};delete record.rest;delete record.holdStart;delete record.timer;db.sessions.push(record);let wk=weekKey(record.startedAt);if(status==='completed'&&weeklyCount(wk)>=db.settings.weeklyGoal&&!db.weeklyBonuses.includes(wk)){db.weeklyBonuses.push(wk);record.xpEarned+=75;record.rewardPointsEarned+=75;record.weeklyBonus=75;let st=streak();if(st>0&&st%4===0){record.xpEarned+=50;record.rewardPointsEarned+=50}}db.lifetimeXP+=record.xpEarned;db.rewardPoints+=record.rewardPointsEarned;db.active=null;completion=record;save();closeSheet();page='Workout';render()}
function completeScreen(){let s=completion;return `<small>${s.status==='partial'?'PROGRESS SAVED':'SESSION COMPLETE'}</small><h1>${s.type}${s.status==='completed'?' complete':''}</h1><p class="target">${mins(s.duration)} min</p><p class="muted">${s.exercises.filter(e=>e.sets.length).length} exercises · ${s.exercises.reduce((n,e)=>n+e.sets.length,0)} sets</p><div class="quiet"><h2>+${s.xpEarned} XP</h2><p class="muted">+${s.rewardPointsEarned} Reward Points</p></div>${s.prs.map(p=>`<div class="quiet"><small class="accent">NEW PR</small><p>${esc(p.name)} · ${p.value}${p.timed?' sec':' reps at '+p.weight+' kg'}</p><small>Previous: ${p.previous} · +25 XP</small></div>`).join('')}<p class="quiet">This week: ${weeklyCount()} / ${db.settings.weeklyGoal} workouts</p><button class="primary" onclick="completion=null;navigate('Dashboard')">Done</button>`}
function plateCalc(target,mode){let rods=mode==='bar'?db.settings.barWeight:db.settings.handleWeight;if(rods===null)return null;let multiplier=mode==='pair'?4:2,counts=db.settings.plates,values=[1.25,1.5,2],best=null;for(let a=0;a<=Math.floor(counts[0]/multiplier);a++)for(let b=0;b<=Math.floor(counts[1]/multiplier);b++)for(let c=0;c<=Math.floor(counts[2]/multiplier);c++){let load=rods+2*(a*1.25+b*1.5+c*2),diff=Math.abs(load-target),n=a+b+c;if(!best||diff<best.diff||diff===best.diff&&n<best.n)best={counts:[a,b,c],load,diff,n,multiplier}}return best}
function exerciseDetails(id,active=false){let def=EXERCISES[id],e=active?db.active.exercises[db.active.index]:{exerciseId:id,variation:db.preferences[id]||def.variants[0],weight:db.loads[id]??def.weight},calc=plateCalc(e.weight,modeFor(e));sheet(`<h2>${esc(name(e))}</h2><div class="demo" role="img" aria-label="Exercise illustration placeholder. Use the written technique cues below."><svg viewBox="0 0 200 150" width="100%" height="100%"><text x="100" y="35" text-anchor="middle" fill="#999ca2" font-size="10">MOVEMENT GUIDE</text><path d="M55 85h90M55 70v30m15-38v46m60-46v46m15-38v30" stroke="#b9cfb3" stroke-width="6" stroke-linecap="round"/><text x="100" y="135" text-anchor="middle" fill="#999ca2" font-size="9">Technique cues below</text></svg></div><ul>${def.cues.map(c=>`<li>${c}</li>`).join('')}</ul><p class="muted">${esc(suggestion(e))}</p><label for="variation">Easier version / substitute / progression</label><select id="variation">${def.variants.map(v=>`<option ${e.variation===v?'selected':''}>${v}</option>`).join('')}</select><label><input id="remember" type="checkbox" style="width:auto;min-height:auto"> Use this instead from now on</label><button onclick="applyVariation('${id}',${active})">Use variation</button><label for="exerciseNote">Personal note</label><textarea id="exerciseNote">${esc(db.notes[id]||'')}</textarea><button class="text" onclick="saveNote('${id}',${active})">Save note</button>${e.weight?`<div class="quiet"><h3>Plate loading</h3>${calc?`<p>${calc.load.toFixed(2)} kg ${def.mode==='pair'?'per dumbbell':'total'}</p><p class="muted">Each end: ${calc.counts.map((n,i)=>n?`${n} × ${[1.25,1.5,2][i]} kg`:'').filter(Boolean).join(' + ')||'no plates'}</p><small>${def.mode==='pair'?'Four ends across two dumbbells.':'Two symmetric ends.'} Uses ${calc.counts.reduce((n,c)=>n+c*calc.multiplier,0)} plates. Closest achievable load; confirm it feels appropriate.</small>`:'<p class="muted">Weigh your rod and enter it in More → Equipment for accurate loading.</p>'}</div>`:''}<div class="quiet"><small>Illustration asset slot: assets/exercises/${id}.svg. Written cues are available now; movement animations are reserved for verified assets.</small></div>`)}
function saveNote(id,active){db.notes[id]=$('exerciseNote').value;if(active)db.active.exercises[db.active.index].notes=db.notes[id];save();toast('Note saved')}
function history(){let year=historyMonth.getFullYear(),month=historyMonth.getMonth(),days=[];for(let i=1;i<=new Date(year,month+1,0).getDate();i++)days.push(dateKey(new Date(year,month,i)));return `<h1>History</h1><div class="row"><button class="text" onclick="changeMonth(-1)" aria-label="Previous month">←</button><h3>${historyMonth.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h3><button class="text" onclick="changeMonth(1)" aria-label="Next month">→</button></div><div class="calendar">${['M','T','W','T','F','S','S'].map(d=>`<small style="text-align:center">${d}</small>`).join('')}</div><div class="calendar">${'<span></span>'.repeat((new Date(year,month,1).getDay()+6)%7)}${days.map(d=>`<button class="day ${statusDay(d)} ${d===dateKey(new Date())?'today':''}" onclick="openDay('${d}')">${Number(d.slice(-2))}</button>`).join('')}</div><p class="muted">Choose a day to inspect or correct a session.</p>${orderSessions().slice(0,8).map(s=>`<div class="listrow"><button onclick="sessionDetails('${s.id}')">${s.type}${s.minimum?' · Minimum':''}<small style="display:block">${fmtTime(s)} · ${s.status}</small></button></div>`).join('')}`}
function changeMonth(n){historyMonth=new Date(historyMonth.getFullYear(),historyMonth.getMonth()+n,1);render()}
function openDay(day){selectedDate=day;let ss=db.sessions.filter(s=>sessionDate(s)===day);sheet(`<h2>${new Date(day+'T12:00:00').toLocaleDateString(undefined,{month:'long',day:'numeric'})}</h2>${ss.length?ss.map(s=>`<div class="listrow"><button onclick="sessionDetails('${s.id}')">${s.type} · ${s.status}<small style="display:block">${fmtTime(s)}</small></button></div>`).join(''):'<p class="muted">No session recorded.</p>'}`)}
function sessionDetails(id){let s=db.sessions.find(s=>s.id===id);sheet(`<small>${s.status.toUpperCase()}</small><h2>${s.type}${s.minimum?' · Minimum':''}</h2><p>${fmtTime(s)}${s.legacy?'':' – '+new Date(s.finishedAt).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit'})}</p><p class="muted">${s.legacy?'Time and performance were not saved by the original app.':mins(s.duration)+' min'}</p>${s.exercises.filter(e=>e.sets.length).map(e=>`<div class="listrow"><p>${esc(name(e))}</p><small>${e.sets.map(x=>EXERCISES[e.exerciseId].timed?x.duration+' sec':x.reps+' reps').join(' · ')} · ${e.sets[0].weight} kg</small><p><small>${esc(e.difficultyFeedback||'')} ${esc(e.notes||'')}</small></p></div>`).join('')}<p>+${s.xpEarned} XP · +${s.rewardPointsEarned} points</p><button class="text" onclick="editSession('${id}')">Correct entry</button><button class="text danger" onclick="deleteSession('${id}')">Delete entry</button>`)}
function editSession(id){let s=db.sessions.find(s=>s.id===id);sheet(`<h2>Correct session</h2><p class="muted">Corrections do not issue more rewards or subtract lifetime XP.</p><label>Workout type</label><select id="editType">${['Push','Pull','Legs','Rest'].map(t=>`<option ${t===s.type?'selected':''}>${t}</option>`).join('')}</select><label>Status</label><select id="editStatus">${['completed','partial','rest'].map(t=>`<option ${t===s.status?'selected':''}>${t}</option>`).join('')}</select><label>Date ${s.legacy?'':'and time'}</label><input id="editDate" type="${s.legacy?'date':'datetime-local'}" value="${s.legacy?s.date:localDatetime(s.startedAt)}">${s.legacy?'':`<label>Finished at</label><input id="editFinish" type="datetime-local" value="${localDatetime(s.finishedAt)}">`}<label>Training duration (minutes)</label><input id="editDuration" type="number" min="0" value="${mins(s.duration)}">${s.exercises.map((e,i)=>`<label>${esc(name(e))} · ${EXERCISES[e.exerciseId].timed?'seconds':'reps'} (comma separated)</label><input id="editSets${i}" value="${e.sets.map(x=>EXERCISES[e.exerciseId].timed?x.duration:x.reps).join(',')}">`).join('')}<button class="primary" onclick="saveCorrection('${id}')">Save correction</button>`)}
function localDatetime(iso){let d=new Date(iso);return dateKey(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
function saveCorrection(id){let s=db.sessions.find(s=>s.id===id),copy=JSON.parse(JSON.stringify(s));copy.type=$('editType').value;copy.status=$('editStatus').value;let dur=Number($('editDuration').value);if(!Number.isFinite(dur)||dur<0)return toast('Enter a valid duration');copy.duration=dur*60;if(s.legacy)copy.date=$('editDate').value;else{let start=new Date($('editDate').value),end=new Date($('editFinish').value);if(!Number.isFinite(+start)||!Number.isFinite(+end)||end<start)return toast('Check session times');copy.startedAt=start.toISOString();copy.finishedAt=end.toISOString()}for(let i=0;i<s.exercises.length;i++){let raw=$('editSets'+i).value,vals=raw.trim()?raw.split(',').map(Number):[];if(vals.some(v=>!Number.isInteger(v)||v<1||v>999)||vals.length!==s.exercises[i].sets.length)return toast('Keep the same set count; enter valid values');vals.forEach((v,j)=>{copy.exercises[i].sets[j][EXERCISES[copy.exercises[i].exerciseId].timed?'duration':'reps']=v})}if(copy.status==='rest'&&copy.type!=='Rest'||copy.status!=='rest'&&copy.type==='Rest')return toast('Rest type and status must match');db.sessions[db.sessions.indexOf(s)]=copy;save();closeSheet();render()}
function deleteSession(id){sheet(`<h2>Delete this entry?</h2><p class="muted">History and consistency will update. Already earned XP and points remain; deleting cannot reissue session rewards.</p><button class="primary" onclick="confirmDelete('${id}')">Delete entry</button>`)}
function confirmDelete(id){db.sessions=db.sessions.filter(s=>s.id!==id);save();closeSheet();render()}
function more(){return `<h1>More</h1><p class="muted">Make it your routine.</p><div class="quiet"><div class="row"><span>Level ${Math.floor(db.lifetimeXP/300)+1} · ${rank()}</span><span>${db.rewardPoints} points</span></div><div class="progress"><i style="width:${db.lifetimeXP%300/3}%"></i></div><small>${db.lifetimeXP} / ${(Math.floor(db.lifetimeXP/300)+1)*300} lifetime XP</small></div><div class="listrow"><button onclick="rewardsSheet()">Rewards</button></div><div class="listrow"><button onclick="progressSheet()">Progress & personal records</button></div><details><summary>Workout settings</summary>${settingInput('weeklyGoal','Weekly workout goal',1,14)}${settingInput('setRest','Rest between sets (seconds)',0,600)}${settingInput('compoundRest','Compound set rest (seconds)',0,600)}${settingInput('exerciseRest','Rest between exercises (seconds)',0,600)}<label><input type="checkbox" style="width:auto;min-height:auto" ${db.settings.readiness?'checked':''} onchange="db.settings.readiness=this.checked;save()"> Ask readiness before starting</label></details><details><summary>Equipment</summary><p class="muted">Rod weights are unknown until you weigh them. Plates are shared across two dumbbells.</p>${settingInput('handleWeight','Dumbbell rod weight (kg)',0,50,.01)}${settingInput('barWeight','Small bar / sponge rod weight (kg)',0,50,.01)}${[1.25,1.5,2].map((v,i)=>`<label>${v} kg plates available</label><input type="number" min="0" max="40" step="1" value="${db.settings.plates[i]}" onchange="setPlate(${i},this)">`).join('')}</details><details><summary>Work & sleep routine</summary><div class="chips">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,i)=>`<button class="${db.settings.workDays.includes(i)?'selected':''}" onclick="toggleWorkDay(${i})">${d}</button>`).join('')}</div>${['shiftStart','shiftEnd','sleep','wake'].map(k=>`<label>${({shiftStart:'Shift start',shiftEnd:'Shift end',sleep:'Usual sleep time (optional)',wake:'Usual wake time (optional)'})[k]}</label><input type="time" value="${db.settings[k]}" onchange="db.settings.${k}=this.value;save()">`).join('')}<p class="muted">${trainingWindow()}</p></details><details><summary>Exercise preferences & notes</summary>${Object.keys(EXERCISES).map(id=>`<div class="listrow"><button onclick="exerciseDetails('${id}')">${esc(db.preferences[id]||EXERCISES[id].name)}</button></div>`).join('')}</details><details><summary>Backup / Restore</summary><p class="muted">Data stays on this device and website origin. Export regularly.</p><button onclick="exportBackup()">Export Backup</button><label for="backupFile">Import JSON backup</label><input id="backupFile" type="file" accept="application/json,.json" onchange="importBackup(this.files[0])"></details><details><summary>App preferences</summary><p class="muted">System reduced-motion settings are respected. Iron Week uses no account, tracking, external fonts, or backend.</p><small>Schema 2 · legacy dates preserved: ${db.migration.importedDates||0}</small></details>`}
function rank(){return ['Iron Rookie','Plate Pusher','Iron Grinder','Steel Regular','Iron Veteran','Iron Elite'][Math.min(5,Math.floor((Math.floor(db.lifetimeXP/300)+1)/5))]}
function settingInput(k,label,min,max,step=1){return `<label>${label}</label><input type="number" min="${min}" max="${max}" step="${step}" value="${db.settings[k]??''}" placeholder="Unknown" onchange="setSetting('${k}',this,${min},${max},${step})">`}
function setSetting(k,el,min,max,step){let v=el.value===''&&k.includes('Weight')?null:Number(el.value);if(v!==null&&(!Number.isFinite(v)||v<min||v>max||step===1&&!Number.isInteger(v))){el.value=db.settings[k]??'';return toast('Check the value')}db.settings[k]=v;save()}
function setPlate(i,el){let n=Number(el.value);if(!Number.isInteger(n)||n<0||n>40)return toast('Use a whole plate count');db.settings.plates[i]=n;save()}
function toggleWorkDay(i){let a=db.settings.workDays;a.includes(i)?a.splice(a.indexOf(i),1):a.push(i);save();render();document.querySelectorAll('details')[2].open=true}
function trainingWindow(){if(db.settings.wake){let [h,m]=db.settings.wake.split(':').map(Number);return `Suggested window: ${String((h+1)%24).padStart(2,'0')}:${String(m).padStart(2,'0')}–${String((h+3)%24).padStart(2,'0')}:${String(m).padStart(2,'0')}, after waking. Adjust for meals and your shift; this is guidance only.`}return 'Add your usual wake time for a gentle training-window suggestion.'}
function rewardsSheet(){sheet(`<h2>Rewards</h2><p class="muted">${db.rewardPoints} spendable points · lifetime XP stays with you.</p>${db.rewards.map(r=>`<div class="listrow"><div class="row"><span>${esc(r.name)}</span><small>${r.cost} points</small></div><small>${esc(r.category||'')} ${esc(r.note||'')}</small><div class="chips"><button onclick="editReward('${r.id}')">Edit</button><button onclick="redeem('${r.id}')" ${db.rewardPoints<r.cost?'disabled':''}>Redeem</button><button onclick="goalReward('${r.id}')">${r.goal?'Active goal':'Set goal'}</button></div></div>`).join('')}<button class="primary" onclick="editReward()">Add Reward</button><h3>Redemption history</h3>${db.redemptions.map(r=>`<p>${esc(r.name)} · ${r.pointsSpent} points<br><small>${new Date(r.redeemedAt).toLocaleString()}</small></p>`).join('')||'<p class="muted">Your next reward is ahead.</p>'}`)}
function editReward(id){let r=db.rewards.find(r=>r.id===id)||{};sheet(`<h2>${id?'Edit':'Add'} reward</h2><label>Name</label><input id="rewardName" maxlength="100" value="${esc(r.name||'')}"><label>Points required</label><input id="rewardCost" type="number" min="1" value="${r.cost||1500}"><label>Category (optional)</label><input id="rewardCategory" value="${esc(r.category||'')}"><label>Note (optional)</label><textarea id="rewardNote">${esc(r.note||'')}</textarea><button class="primary" onclick="saveReward('${id||''}')">Save reward</button>${id?`<button class="text danger" onclick="deleteReward('${id}')">Delete reward</button>`:''}`)}
function saveReward(id){let name=$('rewardName').value.trim(),cost=Number($('rewardCost').value);if(!name||!Number.isInteger(cost)||cost<1)return toast('Enter a name and positive whole point cost');let r=db.rewards.find(r=>r.id===id);if(!r){r={id:uid(),goal:!db.rewards.length};db.rewards.push(r)}Object.assign(r,{name,cost,category:$('rewardCategory').value,note:$('rewardNote').value});save();rewardsSheet()}
function deleteReward(id){if(!confirm('Delete this reward? Redemption history will remain.'))return;db.rewards=db.rewards.filter(r=>r.id!==id);save();rewardsSheet()}
function goalReward(id){db.rewards.forEach(r=>r.goal=r.id===id);save();rewardsSheet()}
function redeem(id){let r=db.rewards.find(r=>r.id===id);if(!r||db.rewardPoints<r.cost)return;if(!confirm(`Redeem ${r.name} for ${r.cost} points?`))return;db.rewardPoints-=r.cost;db.redemptions.unshift({id:uid(),rewardId:r.id,name:r.name,pointsSpent:r.cost,redeemedAt:new Date().toISOString()});save();rewardsSheet()}
function progressSheet(){let ss=completed(),time=db.sessions.reduce((n,s)=>n+s.duration,0),rows=Object.keys(EXERCISES).map(id=>{let entries=[...ss].sort((a,b)=>(a.startedAt||a.date).localeCompare(b.startedAt||b.date)).flatMap(s=>s.exercises.filter(e=>e.exerciseId===id&&e.sets.length).map(e=>({e,s})));if(!entries.length)return '';let last=entries.at(-1),def=EXERCISES[id],compatible=entries.filter(x=>x.e.variation===last.e.variation&&x.e.sets[0].weight===last.e.sets[0].weight),best=x=>Math.max(...x.e.sets.map(s=>def.timed?s.duration:s.reps)),first=compatible[0],delta=best(last)-best(first);return `<div class="listrow"><p>${esc(name(last.e))}</p><small>${best(first)} → ${best(last)} ${def.timed?'sec':'reps'}${def.timed?'':' at '+last.e.sets[0].weight+' kg'} · ${delta>0?'+'+delta:'steady'}</small><p class="muted">${esc(suggestion(last.e))}</p></div>`});let months={};ss.forEach(s=>{let m=sessionDate(s).slice(0,7);months[m]=(months[m]||0)+1});sheet(`<h2>Your progress</h2><p>${ss.length} workouts · ${mins(time)} min trained</p><p class="muted">${streak()} week streak · best month ${Math.max(0,...Object.values(months))} workouts</p>${rows.join('')||'<p class="muted">Log a session to begin tracking performance.</p>'}<h3>Personal records</h3>${db.sessions.flatMap(s=>(s.prs||[]).map(p=>`<p>${esc(p.name)} · ${p.value} ${p.timed?'sec':'reps at '+p.weight+' kg'}<br><small>${fmtTime(s)}</small></p>`)).join('')||'<p class="muted">Your first session establishes a baseline.</p>'}`)}
function download(text,filename){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportBackup(){download(JSON.stringify(db,null,2),'ironweek-'+dateKey(new Date())+'.json')}
let pendingBackup=null;async function importBackup(file){if(!file)return;try{if(file.size>10000000)throw Error('File too large');pendingBackup=validate(JSON.parse(await file.text()));sheet(`<h2>Backup validated</h2><p>${pendingBackup.sessions.length} sessions · ${pendingBackup.lifetimeXP} XP</p><p class="muted">Merge combines session IDs, rewards and redemption IDs. Current settings remain. A safety backup is downloaded first. Cross-device point balances cannot be perfectly reconciled; merge keeps the lower balance to avoid duplicating spendable points.</p><button class="primary" onclick="restoreBackup('merge')">Merge with current data</button><button class="text" onclick="restoreBackup('replace')">Replace with backup</button>`)}catch(e){pendingBackup=null;toast('Invalid backup: '+e.message)}}
function restoreBackup(mode){if(!pendingBackup)return;if(mode==='replace'&&!confirm('Replace current data? A safety backup will download first.'))return;exportBackup();if(mode==='replace')db=pendingBackup;else{let merge=(a,b)=>[...new Map([...b,...a].map(x=>[x.id,x])).values()];db.sessions=merge(db.sessions,pendingBackup.sessions);db.rewards=merge(db.rewards,pendingBackup.rewards);db.redemptions=merge(db.redemptions,pendingBackup.redemptions);db.lifetimeXP=Math.max(db.lifetimeXP,pendingBackup.lifetimeXP);db.rewardPoints=db.sessions.length===0?pendingBackup.rewardPoints:Math.min(db.rewardPoints,pendingBackup.rewardPoints);db.weeklyBonuses=[...new Set([...db.weeklyBonuses,...pendingBackup.weeklyBonuses])];if(!db.active)db.active=pendingBackup.active}pendingBackup=null;save();closeSheet();render();toast('Backup restored')}

document.addEventListener('visibilitychange',()=>{if(document.hidden)save();else render()});window.addEventListener('pagehide',save);



