function nextPreview(){let a=db.active;if(!a)return '';let next=a.stage==='warmup'?warmSteps()[a.warmIndex+1]?.name||name(a.exercises[0]):a.exercises[a.index+1]?name(a.exercises[a.index+1]):'Session summary';return `<p class="next-preview"><small>NEXT</small> ${esc(next)}</p>`}
function skipWarmup(){let a=db.active;if(!a||a.stage!=='warmup'||a.pausedAt)return;a.warmupLog=a.warmupLog||[];a.warmupLog.push({index:a.warmIndex,status:'skipped',at:new Date().toISOString()});a.timer=null;a.timerDone=false;warmNext()}
function skipExercise(){let a=db.active;if(!a||a.stage==='warmup'||a.pausedAt)return;let e=a.exercises[a.index];if(e.sets.length<e.targetSets*(EXERCISES[e.exerciseId].sides?2:1)){e.skipped=true;e.skippedAt=new Date().toISOString()}a.timer=null;a.rest=null;a.timerDone=false;closeSheet();save();advance()}
function workoutMenu(){let a=db.active,e=a.exercises[a.index];sheet(`<h2>Workout options</h2><div class="listrow"><button onclick="closeSheet();togglePause()">${a.pausedAt?'Continue':'Pause'}</button></div><div class="listrow"><button onclick="exitSheet()">Save & exit</button></div>${a.stage==='warmup'?`<div class="listrow"><button onclick="closeSheet();skipWarmup()" ${a.pausedAt?'disabled':''}>Skip this warmup</button></div>`:`<div class="listrow"><button onclick="closeSheet();exerciseNav()">Previous / next exercise</button></div><div class="listrow"><button onclick="closeSheet();exerciseDetails('${e.exerciseId}',true)">Guide & substitute</button></div>${equipmentFor(e)!==EQUIPMENT.BODY?'<div class="listrow"><button onclick="weightSheet()">Weight used</button></div>':''}<div class="listrow"><button onclick="skipExercise()" ${a.pausedAt?'disabled':''}>Skip this exercise</button></div>`}`)}
function weightSheet(){let a=db.active,e=a.exercises[a.index];ensureExercise(e);let choices=setups(modeFor(e)),label=e.equipmentType===EQUIPMENT.PAIR?'kg / dumbbell':e.equipmentType===EQUIPMENT.BAR?'kg total':'kg dumbbell';sheet(`<h2>Weight used</h2><small>CURRENT SETUP</small>${loadVisual(e)}<label for="weightSetup">Achievable setup${e.unconfigured?' (plate weight; rod unweighed)':''}</label><select id="weightSetup">${choices.map((s,i)=>`<option value="${i}" ${Math.abs(s.load-e.weight)<.001?'selected':''}>${s.load.toFixed(2)} ${e.unconfigured?'kg plates + rod':label}</option>`).join('')}</select><div id="weightPreview"></div><p class="muted">Applies to your remaining sets. Earlier sets keep their recorded weights.</p><button class="primary" onclick="applyWeight()">Use this setup</button>`);$('weightSetup').onchange=previewWeight;previewWeight()}
function previewWeight(){let e=db.active.exercises[db.active.index],s=setups(modeFor(e))[Number($('weightSetup').value)];if(s)$('weightPreview').innerHTML=loadVisual({...e,weight:s.load,setup:s,loadNote:''})}
function applyWeight(){let a=db.active,e=a.exercises[a.index],s=setups(modeFor(e))[Number($('weightSetup').value)];if(!s)return;Object.assign(e,{weight:s.load,setup:s,manualLoad:true,loadNote:'Your selected setup for remaining sets.'});save();closeSheet();render();toast('Setup updated for your next set')}
function setTestMode(on){if(on&&!testMode){testBaseline=JSON.parse(JSON.stringify(db));db=JSON.parse(JSON.stringify(db));testMode=true;completion=null;toast('Testing mode: changes will not be saved')}else if(!on&&testMode){db=testBaseline||readData();testBaseline=null;testMode=false;completion=null;chosen=null;minimum=false;toast('Trial discarded. Saved data restored')}render();let ds=document.querySelectorAll('details');if(ds.length)ds[ds.length-1].open=true}
function resetSheet(){sheet(`<h2>${testMode?'Reset trial':'Reset Iron Week'}</h2><p class="muted">${testMode?'Only this trial is cleared. Your saved data stays intact.':'This clears workouts, XP, rewards, preferences and settings on this device. Export a backup first if you want to keep them.'}</p>${testMode?'':'<button onclick="exportBackup()">Export backup</button><label for="resetConfirm">Type RESET to confirm</label><input id="resetConfirm" autocomplete="off" placeholder="RESET">'}<button class="primary" onclick="resetData()">${testMode?'Reset trial':'Reset all app data'}</button>`)}
function resetData(){if(!testMode&&$('resetConfirm').value!=='RESET')return toast('Type RESET to confirm');if(!testMode){try{for(let key of [KEY,'ironweek_xp','ironweek_completedDates'])localStorage.removeItem(key);localStorage.setItem(KEY,JSON.stringify(defaults()))}catch(e){return toast('Reset failed; storage is unavailable')}}db=defaults();completion=null;pendingBackup=null;chosen=null;minimum=false;page='Dashboard';closeSheet();render();toast(testMode?'Trial reset. Saved data unchanged.':'App data reset')}
