/* Reject malformed backup data before it reaches HTML or workout state. */
function validate(d){
 const fail=x=>{throw Error('Invalid backup: '+x)}, obj=(v,k)=>{if(!v||typeof v!=='object'||Array.isArray(v))fail(k);return v},arr=(v,k,max=20000)=>{if(!Array.isArray(v)||v.length>max)fail(k);return v},num=(v,k,min=0,max=Number.MAX_SAFE_INTEGER,int=false)=>{if(!Number.isFinite(v)||v<min||v>max||int&&!Number.isInteger(v))fail(k);return v},str=(v,k,max=10000)=>{if(typeof v!=='string'||v.length>max)fail(k);return v},id=v=>{if(!/^[A-Za-z0-9_-]{1,100}$/.test(str(v,'ID',100)))fail('unsafe ID')},optional=(v,fn)=>v==null?v:fn(v),pick=(v,a,k)=>{if(!a.includes(v))fail(k)},bool=(v,k)=>{if(typeof v!=='boolean')fail(k)},stamp=v=>{if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(str(v,'timestamp',40))||!Number.isFinite(Date.parse(v)))fail('timestamp')},day=v=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(str(v,'date',10))||new Date(v+'T12:00:00').toISOString().slice(0,10)!==v)fail('date')},exid=v=>{if(!Object.hasOwn(EXERCISES,v))fail('exercise ID')},equip=v=>pick(v,['TWO_DUMBBELLS','SINGLE_DUMBBELL','BARBELL','BODYWEIGHT'],'equipment');
 const unsafe=v=>{if(!v||typeof v!=='object')return;for(let k of Object.keys(v)){if(['__proto__','constructor','prototype'].includes(k))fail('unsafe property');unsafe(v[k])}};
 obj(d,'root');unsafe(d);if(d.schemaVersion!==2)fail('schema');d=JSON.parse(JSON.stringify(d));num(d.lifetimeXP,'XP');num(d.rewardPoints,'points');
 function exercise(e){obj(e,'exercise');exid(e.exerciseId);optional(e.variation,v=>str(v,'variation',200));optional(e.notes,v=>str(v,'notes'));optional(e.difficultyFeedback,v=>pick(v,['Easy','Good','Very Hard','Uncomfortable'],'feedback'));optional(e.targetSets,v=>num(v,'target sets',1,10,true));optional(e.weight,v=>num(v,'weight',0,100));optional(e.timedTarget,v=>num(v,'hold target',1,600,true));optional(e.equipmentType,equip);optional(e.loadNote,v=>str(v,'load note',500));optional(e.loadingVersion,v=>num(v,'loading version',0,10,true));for(let k of ['unconfigured','skipped','manualLoad'])optional(e[k],v=>bool(v,k));optional(e.skippedAt,stamp);
 if(e.setup){obj(e.setup,'setup');arr(e.setup.counts,'plate counts',3);if(e.setup.counts.length!==3)fail('plate counts');e.setup.counts.forEach(v=>num(v,'plate count',0,20,true));num(e.setup.load,'load',0,100);pick(e.setup.multiplier,[2,4],'plate ends');optional(e.setup.n,v=>num(v,'plate sum',0,60,true))}
 for(let s of arr(e.sets,'sets',100)){obj(s,'set');num(s.reps,'reps',0,999,true);num(s.duration,'hold duration',0,86400,true);num(s.weight,'set weight',0,100);optional(s.completedAt,stamp);optional(s.side,v=>pick(v,['Left','Right'],'side'));optional(s.equipmentType,equip);optional(s.loadUnknown,v=>bool(v,'unknown load'))}}
 let seen=new Set();for(let s of arr(d.sessions,'sessions')){obj(s,'session');id(s.id);if(seen.has(s.id))fail('duplicate session');seen.add(s.id);pick(s.type,['Push','Pull','Legs','Rest'],'type');pick(s.status,['completed','partial','rest'],'status');num(s.duration,'duration',0,31536000);if(s.legacy)day(s.date);else{stamp(s.startedAt);stamp(s.finishedAt);if(Date.parse(s.finishedAt)<Date.parse(s.startedAt))fail('time order')}arr(s.exercises,'exercises',30).forEach(exercise);for(let k of ['xpEarned','rewardPointsEarned','weeklyBonus'])optional(s[k],v=>num(v,k));if(s.prs)for(let p of arr(s.prs,'records',30)){exid(p.exerciseId);str(p.name,'record name',200);num(p.value,'record',0,86400);num(p.previous,'previous record',0,86400);num(p.weight,'record weight',0,100);optional(p.timed,v=>bool(v,'timed record'))}}
 let rewards=new Set();for(let r of arr(d.rewards,'rewards',1000)){obj(r,'reward');id(r.id);if(rewards.has(r.id))fail('duplicate reward');rewards.add(r.id);str(r.name,'reward name',100);num(r.cost,'cost',1,1e9,true);optional(r.category,v=>str(v,'category',200));optional(r.note,v=>str(v,'reward note'));optional(r.goal,v=>bool(v,'goal'))}
 for(let r of arr(d.redemptions,'redemptions')){obj(r,'redemption');id(r.id);id(r.rewardId);str(r.name,'redemption name',100);num(r.pointsSpent,'spent points',1,1e9,true);stamp(r.redeemedAt)}
 let settings={...defaults().settings,...obj(d.settings||{},'settings')};num(settings.weeklyGoal,'weekly goal',1,14,true);for(let k of ['setRest','compoundRest','exerciseRest'])num(settings[k],k,0,600,true);for(let k of ['handleWeight','barWeight'])optional(settings[k],v=>num(v,k,0,50));arr(settings.plates,'plates',3);if(settings.plates.length!==3)fail('inventory');settings.plates.forEach(v=>num(v,'inventory count',0,40,true));arr(settings.workDays,'work days',7).forEach(v=>num(v,'work day',0,6,true));for(let k of ['shiftStart','shiftEnd','sleep','wake'])if(typeof settings[k]!=='string'||!/^$|^(?:[01]\d|2[0-3]):[0-5]\d$/.test(settings[k]))fail(k);bool(settings.readiness,'readiness');
 for(let k of ['preferences','notes','loads']){d[k]=obj(d[k]||{},k);for(let [key,v]of Object.entries(d[k])){exid(key);if(k==='loads')num(v,'saved load',0,100);else str(v,k,k==='preferences'?200:10000)}}arr(d.weeklyBonuses||[],'bonus weeks').forEach(day);if(d.migration){obj(d.migration,'migration');optional(d.migration.importedDates,v=>num(v,'migration count',0,20000,true));optional(d.migration.legacyXP,v=>num(v,'legacy XP'))}
 if(d.active){let a=obj(d.active,'active');id(a.id);if(seen.has(a.id))fail('active already saved');pick(a.type,['Push','Pull','Legs'],'active type');stamp(a.startedAt);arr(a.exercises,'active exercises',30).forEach(exercise);if(!a.exercises.length)fail('empty active');num(a.index,'index',0,a.exercises.length-1,true);num(a.warmIndex,'warmup index',0,5,true);pick(a.stage,['warmup','work','feedback'],'stage');num(a.pausedMs||0,'paused duration');optional(a.pausedAt,v=>num(v,'pause timestamp'));a.exercises.forEach(e=>num(e.targetSets,'active sets',1,10,true));for(let k of ['timer','rest'])if(a[k]){let t=obj(a[k],'timer');num(t.endsAt,'deadline');optional(t.startedAt,v=>num(v,'timer start'));optional(t.duration,v=>num(v,'timer duration',0,86400));optional(t.id,id);optional(t.sessionId,v=>{id(v);if(v!==a.id)fail('timer session mismatch')});optional(t.exerciseId,v=>{if(!/^warmup-[0-5]$/.test(v))exid(v)});optional(t.type,v=>pick(v,['warmup','movement','transition-rest','set-rest'],'timer type'));optional(t.kind,v=>pick(v,['set','exercise'],'rest kind'));optional(t.setIndex,v=>num(v,'set index',0,100,true));optional(t.previousName,v=>str(v,'previous movement',200))}}
 return {...defaults(),...d,settings,weeklyBonuses:d.weeklyBonuses||[]};
}
