/* Focused workout flow: deadline timers and inventory-aware automatic loading. */
const EQUIPMENT={PAIR:'TWO_DUMBBELLS',SINGLE:'SINGLE_DUMBBELL',BAR:'BARBELL',BODY:'BODYWEIGHT'};
function equipmentFor(e){let v=e.variation||EXERCISES[e.exerciseId].variants[0];if(e.equipmentType)return e.equipmentType;if(e.variation==='Bent-Over Row'||e.variation==='Romanian Deadlift')return EQUIPMENT.BAR;if(EXERCISES[e.exerciseId].timed||/bodyweight|chair squat/i.test(v)||e.exerciseId==='lunge')return EQUIPMENT.BODY;if(/barbell/i.test(v))return EQUIPMENT.BAR;if(/close-grip/i.test(v))return EQUIPMENT.PAIR;if(/supported dumbbell row/i.test(v))return EQUIPMENT.SINGLE;return ({pair:EQUIPMENT.PAIR,single:EQUIPMENT.SINGLE,bar:EQUIPMENT.BAR})[EXERCISES[e.exerciseId].mode]||EQUIPMENT.BODY}
function modeFor(e){return ({TWO_DUMBBELLS:'pair',SINGLE_DUMBBELL:'single',BARBELL:'bar'})[equipmentFor(e)]}
function setups(mode){let rod=mode==='bar'?db.settings.barWeight:db.settings.handleWeight;if(rod===null)rod=0;let ends=mode==='pair'?4:2,all=[];for(let a=0;a<=Math.floor(db.settings.plates[0]/ends);a++)for(let b=0;b<=Math.floor(db.settings.plates[1]/ends);b++)for(let c=0;c<=Math.floor(db.settings.plates[2]/ends);c++)all.push({counts:[a,b,c],load:Number((rod+2*(a*1.25+b*1.5+c*2)).toFixed(3)),multiplier:ends,n:a+b+c});return all.sort((a,b)=>a.load-b.load||a.n-b.n).filter((s,i,arr)=>i===0||s.load!==arr[i-1].load)}
function matchingHistory(e){return orderSessions().filter(s=>s.status==='completed'&&!s.legacy).flatMap(s=>s.exercises.filter(x=>x.exerciseId===e.exerciseId&&x.variation===e.variation&&x.sets.length&&!x.sets.some(s=>s.loadUnknown)&&equipmentFor(x)===equipmentFor(e)&&(x.equipmentType===undefined||x.equipmentType===equipmentFor(e)))).slice(0,2)}
function recommend(e){let def=EXERCISES[e.exerciseId],kind=equipmentFor(e),recent=matchingHistory(e);if(kind===EQUIPMENT.BODY){let target=15;if(def.timed&&recent.length){target=Math.max(10,Math.min(30,Math.min(...recent[0].sets.map(s=>s.duration))));if(recent.length===2&&recent.every(x=>['Easy','Good'].includes(x.difficultyFeedback)&&x.sets.every(s=>s.duration>=target)))target=Math.min(30,target+3);if(recent[0].difficultyFeedback==='Very Hard')target=Math.max(10,target-3)}return {weight:0,equipmentType:kind,setup:null,timedTarget:target,loadNote:''}}
let mode=modeFor(e),all=setups(mode),base=recent[0]?.sets.at(-1).weight??db.loads[e.exerciseId]??def.weight;if(!all.length)return {weight:0,equipmentType:kind,setup:null,loadNote:'Rod weight unknown. Weigh it in More → Equipment; use only a comfortable light setup until then.',unconfigured:true};let nearest=all.reduce((best,s)=>Math.abs(s.load-base)<Math.abs(best.load-base)?s:best,all[0]),selected=nearest,note='';if(recent.length===2&&recent.every(x=>x.sets.every(s=>s.weight===recent[0].sets.at(-1).weight))){let easy=recent.every(x=>['Easy','Good'].includes(x.difficultyFeedback)&&x.sets.every(s=>s.reps>=def.range[1])),hard=recent.every(x=>x.difficultyFeedback==='Very Hard'||x.sets.every(s=>s.reps<def.range[0]));if(easy){let next=all.find(s=>s.load>nearest.load);if(next&&next.load-nearest.load<=Math.max(.5,nearest.load*.15)){selected=next;note='Small progression from your last two sessions.'}else note='Next plate step is large. Keep this load and build controlled reps.'}else if(hard){let lighter=all.filter(s=>s.load<nearest.load).at(-1);if(lighter){selected=lighter;note='Lighter setup after two difficult sessions.'}}}if(recent.some(x=>x.difficultyFeedback==='Uncomfortable'))note='Choose a comfortable substitute. Do not push through pain.';let unknown=(mode==='bar'?db.settings.barWeight:db.settings.handleWeight)===null;return {weight:selected.load,equipmentType:kind,setup:selected,unconfigured:unknown,loadNote:unknown?'Plate weight shown; rod weight is unknown. Weigh it in More → Equipment to calculate the full load.':note}}
function ensureExercise(e){if(e.loadingVersion===1)return;let old=EXERCISES[e.exerciseId];if(e.sets.length){e.weight=e.sets[0].weight;e.equipmentType=equipmentFor(e);let calc=plateCalc(e.weight,modeFor(e));e.setup=calc&&Math.abs(calc.load-e.weight)<.001?calc:null;e.loadNote=e.setup?'':'Recorded load retained for this in-progress exercise.';e.timedTarget=15}else Object.assign(e,recommend(e));e.loadingVersion=1}
function plateSide(counts,reverse=false){let html=[];counts.forEach((n,i)=>{for(let j=0;j<n;j++)html.push(`<span class="load-plate plate-${i}">${[1.25,1.5,2][i]}</span>`)});return (reverse?html.reverse():html).join('')}
function loadVisual(e){if(e.equipmentType===EQUIPMENT.BODY)return '';let label=e.equipmentType===EQUIPMENT.PAIR?'kg / dumbbell':e.equipmentType===EQUIPMENT.BAR?'kg total':'kg dumbbell';let setup=e.setup;return `<section class="load-block"><p class="load-title">${e.weight.toFixed(2).replace(/\.00$/,'')} <small>${e.unconfigured?'kg plates + rod / '+(e.equipmentType===EQUIPMENT.PAIR?'dumbbell':e.equipmentType===EQUIPMENT.BAR?'bar':'dumbbell'):label}</small></p>${setup?`<div class="plate-assembly" role="img" aria-label="${esc(label)}. Each end: ${setup.counts.map((n,i)=>n+' plates of '+[1.25,1.5,2][i]+' kg').join(', ')}"><span class="sleeve"></span>${plateSide(setup.counts,true)}<span class="load-handle">${e.equipmentType===EQUIPMENT.BAR?'ROD':'HANDLE'}</span>${plateSide(setup.counts)}<span class="sleeve"></span></div><small>${e.equipmentType===EQUIPMENT.PAIR?'Same setup on both dumbbells':'Symmetric setup on both ends'} · ${setup.counts.reduce((n,v)=>n+v*setup.multiplier,0)} plates used</small>`:''}${e.loadNote?`<p class="muted load-note">${esc(e.loadNote)}</p>`:''}</section>`}
function timerRemaining(t,now=Date.now()){return Math.max(0,Math.ceil((t.endsAt-now)/1000))}
function timerFormat(n,short=false){return short&&n<60?String(n):`${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
function ring(t,short=false){let n=t.endsAt?timerRemaining(t,db.active?.pausedAt||Date.now()):t.duration,ratio=t.duration?Math.min(1,(t.endsAt?Math.max(0,(t.endsAt-(db.active?.pausedAt||Date.now()))/1000):n)/t.duration):0;return `<div class="countdown" role="timer" aria-label="${n} seconds remaining"><svg viewBox="0 0 240 240" aria-hidden="true"><circle class="ring-track" cx="120" cy="120" r="108"/><circle id="ringProgress" class="ring-progress" cx="120" cy="120" r="108" pathLength="100" stroke-dasharray="100" stroke-dashoffset="${100*(1-ratio)}"/></svg><span id="countdownValue">${timerFormat(n,short)}</span></div>`}
function signalComplete(){if(typeof navigator!=='undefined'&&navigator.vibrate)navigator.vibrate(35)}
function warmSteps(){let a=db.active;return [{name:'March in Place',label:'45 seconds',duration:45},{name:'Arm Circles · Forward',label:'20 seconds',duration:20},{name:'Arm Circles · Backward',label:'20 seconds',duration:20},{name:'Bodyweight Squats',label:'8–10 controlled reps'},{name:'Hip Hinge',label:'8–10 controlled reps'},{name:a.type==='Push'?'Very Light Floor Press':a.type==='Pull'?'Very Light Dumbbell Row':'Slow Bodyweight Squat / Hinge',label:'8 easy reps'}]}
function makeTimer(type,duration){let a=db.active;return {id:uid(),sessionId:a.id,exerciseId:type==='warmup'?'warmup-'+a.warmIndex:a.exercises[a.index].exerciseId,type,duration,startedAt:Date.now(),endsAt:Date.now()+duration*1000,setIndex:a.exercises[a.index]?.sets.length}}
function startCountdown(){let a=db.active;if(!a||a.pausedAt||a.timer||a.rest)return;if(a.stage==='warmup'){let w=warmSteps()[a.warmIndex];if(!w.duration)return;a.timer=makeTimer('warmup',w.duration)}else{let e=a.exercises[a.index];ensureExercise(e);if(!EXERCISES[e.exerciseId].timed||e.sets.length>=e.targetSets)return;a.timer=makeTimer('movement',e.timedTarget)}a.timerDone=false;save();render()}
function setRest(kind,seconds){let a=db.active;a.rest={...makeTimer(kind==='exercise'?'transition-rest':'set-rest',seconds),kind};a.timer=null;a.timerDone=false}
function processTimers(){let a=db.active;if(!a||a.pausedAt)return false;let changed=false;if(a.rest&&!a.rest.startedAt){a.rest.duration=Math.max(0,Math.round((a.rest.endsAt-Date.now())/1000));a.rest.startedAt=Date.now();a.rest.type=a.rest.kind==='exercise'?'transition-rest':'set-rest';a.rest.sessionId=a.id;changed=true}if(a.rest&&Date.now()>=a.rest.endsAt&&!a.rest.notified){a.rest.notified=true;signalComplete();changed=true}let t=a.timer;if(t&&Date.now()>=t.endsAt){a.timer=null;a.timerDone=true;if(t.type==='movement'){let e=a.exercises[a.index];if(e.exerciseId===t.exerciseId&&e.sets.length===t.setIndex){appendSet(t.duration,true);a.timerDone=true}}signalComplete();changed=true}if(changed)save();return changed}
function workout(){let a=db.active;if(!a)return completion?completeScreen():`<h1>Your next session</h1><p class="muted">${chosen||nextType()} · ${minimum?'Minimum':'Full workout'}</p><button class="primary" onclick="startCheck()">Start Workout</button><button class="text" onclick="choose()">Change workout</button>`;processTimers();let menu=`<div class="row workout-toolbar"><small>${a.type.toUpperCase()}${a.minimum?' · MINIMUM':''}</small><button class="text" aria-label="Workout options" onclick="workoutMenu()">•••</button></div>`;if(a.pausedAt)return `${menu}<h1>Paused</h1><p class="muted">Your session and countdown are saved.</p><button class="primary" onclick="togglePause()">Continue</button>`;
if(a.stage==='warmup'){let w=warmSteps()[a.warmIndex];return `${menu}<small>LOW-IMPACT WARMUP</small><h1>${w.name}</h1>${w.duration?ring(a.timer||{duration:a.timerDone?0:w.duration},true):`<p class="target">${w.label}</p>`}<p class="muted">${a.timerDone?'Movement complete':'Easy movement · no jumping'}</p>${a.timer?'<p class="muted">Countdown running</p>':`<button class="primary" onclick="${w.duration&&!a.timerDone?'startCountdown()':'warmNext()'}">${w.duration&&!a.timerDone?'Start':a.warmIndex===warmSteps().length-1?'Begin lifting':'Continue'}</button>`}<div class="row"><button class="text" onclick="skipWarmup()">Skip warmup</button><button class="text" onclick="aSkipWarm()">Already warmed up</button></div>${nextPreview()}`}
let e=a.exercises[a.index];ensureExercise(e);let def=EXERCISES[e.exerciseId],p=previous(e),done=e.sets.length>=e.targetSets*(def.sides?2:1);
if(a.rest){let n=timerRemaining(a.rest),transition=a.rest.kind==='exercise';return `${menu}${transition&&a.rest.previousName?`<small>${esc(a.rest.previousName)} COMPLETE</small>`:''}<h1>${n?'Rest':'Rest complete'}</h1>${ring(a.rest)}<small>NEXT</small><p>${esc(name(e))}</p>${transition?'':`<p class="muted">Set ${Math.floor(e.sets.length/(def.sides?2:1))+1} of ${e.targetSets}${def.sides?' · '+(e.sets.length%2?'Right':'Left'):''}</p>`}<button class="primary" onclick="endRest()">${n?'Skip Rest':transition?'Continue':'Start Set'}</button>${n?'':'<p class="muted">Start when ready.</p>'}`}
if(a.stage==='feedback')return `${menu}<small>EXERCISE COMPLETE</small><h1>${esc(name(e))}</h1><p class="muted">How did it feel?</p><div class="chips">${['Easy','Good','Very Hard','Uncomfortable'].map(r=>`<button onclick="feedback('${r}')">${r}</button>`).join('')}</div>`;
if(e.skipped)return `${menu}<h1>${esc(name(e))}</h1><p class="muted">Skipped · recorded sets retained.</p><button class="primary" onclick="advance()">Continue</button>${nextPreview()}`;
if(done)return `${menu}<h1>${esc(name(e))}</h1><p class="muted">${e.sets.length} sets logged</p><button class="primary" onclick="advance()">${a.index===a.exercises.length-1?'Review session':'Next exercise'}</button>`;
return `${menu}<h1>${esc(name(e))}</h1><p class="muted">Set ${Math.floor(e.sets.length/(def.sides?2:1))+1} of ${e.targetSets}${def.sides?' · '+(e.sets.length%2?'Right':'Left'):''}</p><p class="target">${def.range.join('–')} ${def.timed?'seconds':'reps'}${def.sides?' per side':''}</p>${def.timed?`${ring(a.timer||{duration:e.timedTarget},true)}${a.timer?'<p class="muted">Hold comfortably. Stop before form breaks.</p><button class="text" onclick="stopMovement()">End hold early</button>':`<button class="primary" onclick="startCountdown()">Start</button>`}`:`${loadVisual(e)}<button class="demo-link text" onclick="exerciseDetails('${e.exerciseId}',true)">Movement guide ↗</button>${p?`<div class="previous"><small>PREVIOUS</small><p>${p.sets.map(s=>s.reps).join(' · ')} reps${p.sets[0].weight?' · '+p.sets[0].weight+' kg':''}</p></div>`:''}<label for="setValue">Reps completed</label><input id="setValue" type="number" min="1" max="999" inputmode="numeric" value="${p?.sets[e.sets.length]?.reps||def.range[0]}"><button class="primary" onclick="logSet()">Log Set</button>`}${def.timed&&p?`<small>Previous: ${p.sets.map(s=>s.duration+' sec').join(' · ')}</small>`:''}${e.sets.length?`<p class="muted">Today: ${e.sets.map(s=>def.timed?s.duration+' sec':s.reps+' @ '+s.weight+' kg'+(s.loadUnknown?' plates':'')).join(' · ')}</p>`:''}<div class="row exercise-footer">${nextPreview()}<button class="text" onclick="skipExercise()">Skip exercise</button></div>`}
function warmNext(){let a=db.active;if(a.timer)return;if(a.warmIndex<warmSteps().length-1)a.warmIndex++;else a.stage='work';a.timerDone=false;save();render()}
function aSkipWarm(){let a=db.active;a.stage='work';a.timer=null;a.timerDone=false;save();render()}
function appendSet(v,timed=false){let a=db.active,e=a.exercises[a.index],def=EXERCISES[e.exerciseId];if(e.skipped)return;ensureExercise(e);if(e.sets.length>=e.targetSets*(def.sides?2:1))return;e.sets.push({reps:timed?0:v,duration:timed?v:0,weight:e.weight,equipmentType:e.equipmentType,loadUnknown:!!e.unconfigured,side:def.sides?(e.sets.length%2?'Right':'Left'):null,completedAt:new Date().toISOString()});a.timer=null;if(e.sets.length>=e.targetSets*(def.sides?2:1))a.stage='feedback';else setRest('set',def.compound?db.settings.compoundRest:db.settings.setRest);save()}
function logSet(){let a=db.active;if(!a||a.rest||a.stage!=='work'||a.pausedAt)return;let e=a.exercises[a.index];if(EXERCISES[e.exerciseId].timed)return;let v=Number($('setValue').value);if(!Number.isInteger(v)||v<1||v>999)return toast('Enter valid completed reps.');appendSet(v);render()}
function stopMovement(){let a=db.active,t=a.timer;if(!t||t.type!=='movement')return;let actual=Math.min(t.duration,Math.floor((Date.now()-t.startedAt)/1000));if(actual<1){a.timer=null;save();render();return}appendSet(actual,true);signalComplete();render()}
function endRest(){if(!db.active||db.active.pausedAt)return;db.active.rest=null;db.active.timerDone=false;save();render()}
function advance(){let a=db.active;if(a.index<a.exercises.length-1){let prev=name(a.exercises[a.index]);a.index++;a.stage='work';setRest('exercise',db.settings.exerciseRest);a.rest.previousName=prev;ensureExercise(a.exercises[a.index]);save();render()}else reviewSession()}
function jumpExercise(i){let a=db.active;if(a.timer)return toast('Pause or finish the current timer first.');closeSheet();if(i!==a.index){a.index=i;a.stage='work';setRest('exercise',db.settings.exerciseRest);ensureExercise(a.exercises[i])}save();render()}
function togglePause(){let a=db.active;if(a.pausedAt){let delta=Date.now()-a.pausedAt;a.pausedMs+=delta;for(let t of [a.rest,a.timer])if(t){t.startedAt+=delta;t.endsAt+=delta}a.pausedAt=null}else{processTimers();a.pausedAt=Date.now()}save();render()}
function pauseExit(){processTimers();if(!db.active.pausedAt)db.active.pausedAt=Date.now();save();closeSheet();page='Dashboard';render()}
function applyVariation(id,active){let v=$('variation').value;if($('remember').checked)db.preferences[id]=v;if(active){let a=db.active,e=a.exercises[a.index];if(e.sets.length||a.timer){db.preferences[id]=v;toast('Saved for next session; current logged movement stays consistent.')}else{e.variation=v;e.equipmentType=null;e.loadingVersion=null;ensureExercise(e)}}save();closeSheet();render()}
function hydrateWorkout(){if(!db.loadGuideVersion){for(let id of ['row','rdl'])if(Number.isFinite(db.loads[id]))db.loads[id]=db.loads[id]/2;db.loadGuideVersion=1;save()}let a=db.active;if(!a)return;if(a.flowVersion!==1){if(a.stage==='warmup')a.warmIndex=0;if(a.holdStart){let now=a.pausedAt||Date.now(),passed=Math.max(0,Math.floor((now-a.holdStart)/1000)),duration=Math.max(15,passed);a.timer={...makeTimer('movement',duration),startedAt:a.holdStart,endsAt:a.holdStart+duration*1000};delete a.holdStart}a.flowVersion=1}a.exercises.forEach(ensureExercise);save()}
function updateCountdown(){let a=db.active;if(!a||a.pausedAt)return;if(processTimers()){if(page==='Workout')render();return}if(page!=='Workout')return;let t=a.rest||a.timer;if(t&&$('countdownValue')){let n=timerRemaining(t);$('countdownValue').textContent=timerFormat(n,t.type==='warmup'||t.type==='movement');$('ringProgress').setAttribute('stroke-dashoffset',100*(1-(t.duration?Math.min(1,Math.max(0,(t.endsAt-Date.now())/1000)/t.duration):0)))}}
hydrateWorkout();setInterval(updateCountdown,100);render();
